version: '3.8'

services:
  backend:
    build: .
    container_name: shortlink_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./shortlink.db:/app/shortlink.db
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    container_name: shortlink_redis
    ports:
      - "6379:6379"