"""Add last_accessed to links

Revision ID: f2f54c264a3a
Revises: 41cf6d727fea
Create Date: 2026-04-19 18:33:24.772923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f54c264a3a'
down_revision: Union[str, Sequence[str], None] = '41cf6d727fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_accessed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'last_accessed')
    # ### end Alembic commands ###
