name: Run Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pip install Poetry
      
      - name: Install dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      
      - name: Run tests
        run: poetry run pytest -v
        env:
          PYTEST_RUNNING: "true"